package drivers

import (
	_ "github.com/OpenListTeam/OpenList/v4/drivers/115"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/115_share"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/123"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/123_link"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/123_share"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/139"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/189"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/189pc"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/alias"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/alist_v2"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/alist_v3"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/aliyundrive"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/aliyundrive_open"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/aliyundrive_share"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/baidu_netdisk"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/baidu_photo"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/baidu_share"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/chaoxing"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/cloudreve"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/crypt"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/dropbox"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/ftp"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/google_drive"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/google_photo"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/ilanzou"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/ipfs_api"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/lanzou"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/local"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/mediatrack"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/mega"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/mopan"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/netease_music"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/onedrive"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/onedrive_app"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/pikpak"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/pikpak_share"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/quark_uc"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/quqi"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/s3"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/seafile"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/sftp"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/smb"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/teambition"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/terabox"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/thunder"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/thunderx"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/trainbit"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/url_tree"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/uss"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/virtual"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/vtencent"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/webdav"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/weiyun"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/wopan"
	_ "github.com/OpenListTeam/OpenList/v4/drivers/yandex_disk"
)

// All do nothing,just for import
// same as _ import
func All() {

}
